In [9]:
import numpy as np
a = np.random.rand(4,3,2)
print a
a = a.reshape((a.shape[0],-1))
print a
print a + np.arange(6)

[[[ 0.19148534  0.76863297]
  [ 0.81129259  0.93159992]
  [ 0.1261606   0.27549578]]

 [[ 0.50594988  0.76063875]
  [ 0.60058112  0.05068866]
  [ 0.73237207  0.94019185]]

 [[ 0.15662568  0.37802091]
  [ 0.91160151  0.56272205]
  [ 0.38844616  0.87336857]]

 [[ 0.75221502  0.67323612]
  [ 0.11236141  0.11963229]
  [ 0.92695689  0.71241831]]]
[[ 0.19148534  0.76863297  0.81129259  0.93159992  0.1261606   0.27549578]
 [ 0.50594988  0.76063875  0.60058112  0.05068866  0.73237207  0.94019185]
 [ 0.15662568  0.37802091  0.91160151  0.56272205  0.38844616  0.87336857]
 [ 0.75221502  0.67323612  0.11236141  0.11963229  0.92695689  0.71241831]]
[[ 0.19148534  1.76863297  2.81129259  3.93159992  4.1261606   5.27549578]
 [ 0.50594988  1.76063875  2.60058112  3.05068866  4.73237207  5.94019185]
 [ 0.15662568  1.37802091  2.91160151  3.56272205  4.38844616  5.87336857]
 [ 0.75221502  1.67323612  2.11236141  3.11963229  4.92695689  5.71241831]]


In [10]:
b['a':1, 'b':2, 'c':3]
print b['a','b']

NameError: name 'b' is not defined

In [11]:
for i in range(1, 5):
    print i

1
2
3
4


In [14]:
print 'w'+'a'

wa


In [15]:
a = [1, 2, 3]
b = [0]
b += a
b.append(5)
print b

[0, 1, 2, 3, 5]


In [16]:
print np.sum([1,2,3])

6
