In [19]:
import numpy as np
def dist(x, y):
    return np.sqrt(np.power((x - y), 2).sum())
    
    
a = np.array([1, 2, 3, 4])
b = np.array([0, 1, 2, 3])
print dist(a, b - 1)

4.0


In [86]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],
            [4, 5, 6]])
print np.argmax(b,axis=1)

[2 2]


In [75]:
a = [1, 2, 3, 4]
print a[0:3] + a[4:]

[1, 2, 3]


In [87]:
a = [1, 2, 3]
b = [4, 5, 6]
print zip(a, b)

[(1, 4), (2, 5), (3, 6)]


In [18]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])
print a[[0, 1],[1, 2]]
print a.sum(axis=1)

[2 6]
[ 6 15]


In [101]:
a = np.array([1, 2, 3])
print a.shape
print a.reshape(a.shape[0], 1).shape
a.reshape(a.shape[0], 1).repeat(3, axis=1)

(3,)
(3, 1)


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [8]:
a = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
b = np.array([1, 2, 3])

print a
print b
print np.outer(a.reshape((9,1)), b)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [2 4 6]
 [2 4 6]
 [2 4 6]
 [3 6 9]
 [3 6 9]
 [3 6 9]]


In [16]:
a = np.array([1, 2, 3])
print a.shape
print a.reshape(a.shape[0], 1) * a
print a.dot(a)

(3,)
[[1 2 3]
 [2 4 6]
 [3 6 9]]
14


In [33]:
a = np.random.randn(3, 2)
b = np.sum(a, axis=1)
print a
print np.argmax(a, axis=0)

[[-0.2842857   0.45424684]
 [ 0.91289134  1.10391607]
 [ 1.2623387   0.86696035]]
[2 1]


In [1]:
from notebook.auth import passwd
passwd()

Enter password: ········
Verify password: ········


'sha1:1ffec54702ac:e8f2945400080680d242113753f6361582182c24'